### ISSUE TITLE
Why is a X server needed for gui 2?

### ISSUE THREAD

**Issue by HawkingJan** [JvanKatwijk/dab-rpi#7]
I'm using your program together with a Rafael Micro R820T tuner on my Raspberry Pi. In principle it seems to work fine (I just started using it).
Sometimes I connect to my Pi with and sometimes without X connection.
To control the device in both cases I compiled the code in one directory with 
CONFIG          += gui_1
and in an other with
CONFIG          += gui_2
However, even in the directory with gui_2 I get
"dab-rpi-0.997: cannot connect to X server"
Why is there an X server needed if I want to control the program via the command line?

**Comment by JvanKatwijk** [comment]
The gi_2 software is for 99 percent the same as the software for gui_1, while there is no "main" widget created, there are widgets for the devices, however, invisible.  The software is still a Qt application,
with all Qt requirements.
While it sure is possible to create a version without any reference to Qt, that would be a major rewrite of the code (an interesting exercition though)
