### ISSUE TITLE
Gui 1 works but gui 2 does not (could not find useful data in channel)

### ISSUE THREAD

**Issue by HawkingJan** [JvanKatwijk/dab-rpi#9]
I'm using your program on an Raspberry Pi 2.
My current ~/.dab-rpi.ini looks like the following:

```
[General]
band=Band III
channel=11D
device=dabstick
dabMode=1

[dabstickSettings]
externalGain=496
autogain=autogain off
f_correction=0
KhzOffset=0

[gui_2]
channel=11D
programName=BR-KLASSIK
soundChannel=snd_rpi_hifiberry_dacplus
deviceGain=20
```

If I start the version compiled with gui 1 I can select "BR-KLASSIK" and listen to it. That this station exists is also confirmed in the output
> we have now DAB+
> we found for BR-KLASSIK       serviceId d314

However, If I run  (without any parameters, as they are given in the ~/.dab-rpi.ini file)  the version that I compiled in an other folder with gui 2I get

> running sdr-j DAB-rpi(+)  0.9975
> Starting 1
> 
> could not find useful data in channel 11DofdmProcessor is closing down
> ofdm decoder is closing down now
> It is done

Besides the missing line break after the channel name (11D) I don't understand why it does not find useful data using GUI 2? According to the manual the default device, band and mode should be like the one for GUI 1. I also tested other channels and station names (to make sure that is not an issue with encodig of the "-" in the programs name) but they gave the same error.
Do you have an idea what I should look for?

**Comment by JvanKatwijk** [comment]
There was an issue with the gain settings. Apparently setting the gain for dabsticks does not last when changing the frequency. The issue did not appear with the airspy, it also appeared with the sdrplay.
Afaik, the issue is now solved.
